### ISSUE TITLE
IndexError when checking multiple modules

### ISSUE THREAD

**Issue by bwrsandman** [nbessi/openerp-conventions#7]
## Error

```
Traceback (most recent call last):
  File "/usr/bin/flake8", line 9, in <module>
    load_entry_point('flake8==2.1.0', 'console_scripts', 'flake8')()
  File "/usr/lib/python2.7/site-packages/flake8/main.py", line 32, in main
    report = flake8_style.check_files()
  File "/usr/lib/python2.7/site-packages/pep8.py", line 1622, in check_files
    self.input_dir(path)
  File "/usr/lib/python2.7/site-packages/pep8.py", line 1658, in input_dir
    runner(os.path.join(root, filename))
  File "/usr/lib/python2.7/site-packages/flake8/engine.py", line 73, in input_file
    return fchecker.check_all(expected=expected, line_offset=line_offset)
  File "/usr/lib/python2.7/site-packages/pep8.py", line 1366, in check_all
    self.check_ast()
  File "/usr/lib/python2.7/site-packages/pep8.py", line 1347, in check_ast
    if not noqa(self.lines[lineno - 1]):
IndexError: list index out of range
```
## Steps to reproduce
- Run `flake8 .` in a directory which contains multiple modules, such as openobject-addons
## Expected output
- Flake8 check of each python file in any of the subdirectories
## Actual output
- Flake8 will start checking of each python file in any of the subdirectories
- After a few modules, it will crash with an `IndexError`

**Comment by nbessi** [comment]
I'm not sure that it is related to openerp-convetions can zouplease do the
same test without the extention

Regards

Nicolas

2014-02-06 Sandy notifications@github.com:

**Comment by nbessi** [comment]
Ok it is actually a flake8 extention bug. It seems also easy to avoid by ignoring empty files

**Comment by florentx** [comment]
if you upgrade `pep8` dependency to 1.5, it's fixed.

https://github.com/jcrocholl/pep8/issues/240

**Comment by nbessi** [comment]
Thanks I will try.

Regards

Nicolas

2014-03-26 18:15 GMT+01:00 Florent Xicluna notifications@github.com:
